from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from config.configuration import MODEL_NAME

load_dotenv()

llm = HuggingFaceEndpoint(
    repo_id=MODEL_NAME,
    task="text-generation"
)

model = ChatHuggingFace(llm=llm)


# ---------------------------------------------------------
# Prompt 1: Generate a detailed report
# ---------------------------------------------------------

# Create a prompt template with a dynamic {topic} placeholder.
# The value for {topic} will be provided when the prompt is invoked.
template1 = PromptTemplate(
    template="Write a detailed report on {topic}",
    input_variables=["topic"]
)


# ---------------------------------------------------------
# Prompt 2: Generate a summary of the report
# ---------------------------------------------------------

# Create another prompt template with a dynamic {report} placeholder.
# The report generated by Prompt 1 will be passed into this prompt.
template2 = PromptTemplate(
    template="Write a brief summary on the following text\n{report}",
    input_variables=["report"]
)


# Invoke Prompt 1 by providing the topic.
# This replaces {topic} with "Black Hole".
prompt1 = template1.invoke({"topic": "Black Hole"})

# Send the first prompt to the LLM to generate a detailed report.
result = model.invoke(prompt1)


# Invoke Prompt 2 by providing the report generated by Prompt 1.
# This replaces {report} with the content of the generated report.
prompt2 = template2.invoke({"report": result.content})

# Send the second prompt to the LLM.
# The model will generate a brief summary of the detailed report.
result = model.invoke(prompt2)


# Print the final summary.
print(result.content)